### ISSUE TITLE
how to contribute?

### ISSUE THREAD

**Issue by krishnakatyal** [petebankhead/qupath-docs#1]
I WOULD LIKE TO CONTRIBUTE,REALLY FIND QUPATH GREAT

**Comment by petebankhead** [comment]
Thanks, this is just a temporary repo while I try out readthedocs, so it isn't announced anywhere for now. Hope to have a new repo for documentation with contributing guidelines soon.

**Comment by petebankhead** [comment]
Note that for QuPath more generally there are already contributing guidelines at https://github.com/qupath/qupath/blob/master/CONTRIBUTING.md
